version: '3'
services:
  mongodb:
     image: mongo
     container_name: tickets_lite_mongo
     restart: always
     ports:
       - "5001:27017"
  ticketsliteapi:
    image: api:latest
    depends_on:
       - mongodb
    container_name: tickets_lite_api
    restart: always
    ports:
      - "5000:3000"